# Generated by Django 5.2.7 on 2025-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='color',
            field=models.CharField(default='Red', max_length=50),
        ),
    ]
