# Generated by Django 5.2.7 on 2025-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_product_sizes_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Cotton', max_length=100),
        ),
    ]
