# Generated by Django 5.2.7 on 2025-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_product_sizes_alter_productreview_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Default', max_length=50),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='color',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
