# Generated by Django 5.2.7 on 2025-12-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_product_color_alter_productimages_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
