# Generated by Django 5.2.7 on 2025-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_productimages_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='color',
            field=models.CharField(default='Black', max_length=50),
        ),
    ]
