# Generated by Django 5.2.7 on 2025-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_cartorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
