# Generated by Django 5.2.7 on 2025-12-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_cartorder_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.cartorder'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=199, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(default='Processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=199, max_digits=10),
        ),
    ]
