# Generated by Django 5.2.7 on 2025-12-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_cartorderitems_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
