# Generated by Django 5.2.7 on 2025-12-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_cartorder_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='invoice_no',
        ),
    ]
