# Generated by Django 5.2.7 on 2025-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_cartorder_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
