# Generated by Django 5.2.7 on 2025-12-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_cartorder_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
