# Generated by Django 5.2.7 on 2025-12-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_cartorder_color_cartorder_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='size',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
