# Generated by Django 5.2.7 on 2025-12-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Prosessing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=50),
        ),
    ]
