# Generated by Django 5.2.7 on 2025-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_cartorderitems_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(default='cart-order-items.jpg', upload_to='cart-order-items'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Prosessing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=50),
        ),
    ]
