# Generated by Django 5.2.7 on 2025-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_cartorderitems_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
