# Generated by Django 5.2.7 on 2025-12-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_address_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
