# Generated by Django 5.2.7 on 2025-12-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_cartorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(default='', upload_to='cart-order-items'),
        ),
    ]
