# Generated by Django 5.2.7 on 2025-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_cartorder_address_cartorder_city_cartorder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
