# Generated by Django 5.2.7 on 2025-12-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_address_city_address_state_address_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
