# Generated by Django 5.2.7 on 2025-12-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_remove_address_city_remove_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
