# Generated by Django 5.2.7 on 2025-12-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_cartorder_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='address',
            field=models.CharField(default='123, Main Street', max_length=255),
        ),
    ]
