# Generated by Django 5.2.7 on 2025-12-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_cartorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
