# Generated by Django 5.2.7 on 2025-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_profile.png', upload_to='image')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
