# Generated by Django 5.2.7 on 2025-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_profile_image_alter_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
